name: Common Service CD to GKE

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

  build-image:
    runs-on: ubuntu-latest
    needs: auth
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --push \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.service }}:${{ inputs.tag }} .

  # asia-east1-docker.pkg.dev/cnad-group3/cnad-prod-repo/image:tag
  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --region ${{ secrets.GKE_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl set image deployment/${{ inputs.service }} \
            ${{ inputs.service }}=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.service }}:${{ inputs.tag }}
          kubectl rollout status deployment/${{ inputs.service }}
